<?php

//VIDEO-MUSIC
if (VIDEOMUSIC=='YES')
{
	function Insert()
	{
		echo WARNINGBEFOREINSERT."&nbsp;<a class=bouton_htdtc href=\"javascript:void(0)\" onmouseover=\"select2.src='inc/gfx/opentriangle_over.gif',AffBulle('<table class=insert_htdtc cellspacing=2 cellpadding=2 onclick=\'HideBulle()\'><tr><td align=right colspan=7><img class=shadow_htdtc alt=Fermer onmouseover=close2.src=\'inc/gfx/close_over.gif\' onmouseout=close2.src=\'inc/gfx/close.gif\' name=close2 src=\'inc/gfx/close.gif\' align=abstop border=0 onClick=\'HideBulle()\'></td></tr><tr><td>&nbsp;<img src=\'inc/gfx/apphoto.gif\' align=absmiddle border=0>";ShowFoldersForInsert(IMGDIR,'apphoto','pics'); echo "</td></tr><tr><td>&nbsp;<img src=\'inc/gfx/pdf_x.gif\' align=absmiddle border=0>";ShowFoldersForInsert(PDFDIR,'apphoto','pdf'); echo "<tr><td>&nbsp;<img src=\'inc/gfx/page_x.gif\' align=absmiddle border=0>";ShowFoldersForInsert(POPDIR,'page_x','pop'); echo "<tr><td>&nbsp;<img src=\'inc/gfx/music.gif\' align=absmiddle border=0>";ShowFoldersForInsert(SOUNDDIR,'music','Music');  echo "<tr><td>&nbsp;<img src=\'inc/gfx/videos.gif\' align=absmiddle border=0>";ShowFoldersForInsert(VIDEODIR,'videos','videos');  echo "</td></tr><tr><td height=10 class=corps_htdtc></td></tr></table>')\" onmouseout=\"select2.src='inc/gfx/opentriangle.gif'\"><b>&nbsp;Inserer&nbsp;<img name=select2 src=\"inc/gfx/opentriangle.gif\" border=0/>&nbsp;</b></a>";
		//echo "&nbsp;<a class=bouton_htdtc href=\"javascript:void(0)\" onmouseover=\"select2.src='inc/gfx/opentriangle_over.gif',AffBulle('<table class=insert_htdtc cellspacing=2 cellpadding=2 onclick=\'HideBulle()\'><tr><td align=right colspan=7><img class=shadow_htdtc alt=Fermer onmouseover=close2.src=\'inc/gfx/close_over.gif\' onmouseout=close2.src=\'inc/gfx/close.gif\' name=close2 src=\'inc/gfx/close.gif\' align=abstop border=0 onClick=\'HideBulle()\'></td></tr><tr><td>&nbsp;<img src=\'inc/gfx/apphoto.gif\' align=absmiddle border=0>";ShowFoldersForInsert(IMGDIR,'apphoto','pics'); echo "</td></tr><tr><td>&nbsp;<img src=\'inc/gfx/pdf_x.gif\' align=absmiddle border=0>";ShowFoldersForInsert(PDFDIR,'apphoto','pdf'); echo "<tr><td>&nbsp;<img src=\'inc/gfx/page_x.gif\' align=absmiddle border=0>";ShowFoldersForInsert(POPDIR,'page_x','pop'); echo "<tr><td>&nbsp;<img src=\'inc/gfx/music.gif\' align=absmiddle border=0>";ShowFoldersForInsert(SOUNDDIR,'music','Music');  echo "<tr><td>&nbsp;<img src=\'inc/gfx/videos.gif\' align=absmiddle border=0>";ShowFoldersForInsert(VIDEODIR,'videos','videos');  echo "</td></tr><tr><td height=10 class=corps_htdtc></td></tr></table>')\" onmouseout=\"select2.src='inc/gfx/opentriangle.gif'\"><b>&nbsp;Inserer&nbsp;<img name=select2 src=\"inc/gfx/opentriangle.gif\" border=0/>&nbsp;</b></a>";
	}

	function OtherFolders()
	{
		echo "<a class=bouton_htdtc href=\"javascript:void(0)\" onmouseover=\"selecto.src='inc/gfx/folder2_over.gif',AffBulle('<table class=insert_htdtc cellspacing=1 cellpadding=1 onclick=\'HideBulle()\'><tr><td align=right><img class=shadow_htdtc alt=Fermer onMouseOver=close3.src=\'inc/gfx/close_over.gif\' onmouseout=close3.src=\'inc/gfx/close.gif\' name=close3 src=\'inc/gfx/close.gif\' align=abstop border=0 onclick=\'HideBulle()\'></td><tr><tr><td align=center><img src=\'inc/gfx/dossier.gif\' align=absmiddle border=0>&nbsp;<b>".DIRBUTTONTITLE."&nbsp;</b></td></tr>";ShowFolders(IMGDIR,'apphoto','Pics'); ShowFolders(PDFDIR,'pdf_x','Pdf'); ShowFolders(POPDIR,'page_x','Pop'); ShowFolders(SOUNDDIR,'music','Music'); ShowFolders(VIDEODIR,'videos','Videos'); echo "<tr><td height=5></td></tr></table>')\" onmouseout=\"selecto.src='inc/gfx/folder2.gif'\"><img name=selecto src=\"inc/gfx/folder2.gif\" border=0 align=middle /></a>";
	}
}
else
{
	/* WITHOUT VIDEO-MUSIC*/
	function Insert()
	{
		echo WARNINGBEFOREINSERT."&nbsp;<a class=bouton_htdtc href=\"javascript:void(0)\" onmouseover=\"select2.src='inc/gfx/opentriangle_over.gif',AffBulle('<table class=insert_htdtc cellspacing=2 cellpadding=2 onclick=\'HideBulle()\'><tr><td align=right colspan=7><img class=shadow_htdtc alt=Fermer onmouseover=close2.src=\'inc/gfx/close_over.gif\' onmouseout=close2.src=\'inc/gfx/close.gif\' name=close2 src=\'inc/gfx/close.gif\' align=abstop border=0 onclick=\'HideBulle()\'></td></tr><tr><td>&nbsp;<img src=\'inc/gfx/apphoto.gif\' align=absmiddle border=0>";ShowFoldersForInsert(IMGDIR,'apphoto','pics'); echo "</td></tr><tr><td>&nbsp;<img src=\'inc/gfx/pdf_x.gif\' align=absmiddle border=0>";ShowFoldersForInsert(PDFDIR,'apphoto','pdf'); echo "<tr><td>&nbsp;<img src=\'inc/gfx/page_x.gif\' align=absmiddle border=0>";ShowFoldersForInsert(POPDIR,'page_x','pop'); echo "</td></tr><tr><td height=10 class=corps_htdtc></td></tr></table>')\" onmouseout=\"select2.src='inc/gfx/opentriangle.gif'\"><b>&nbsp;Inserer&nbsp;<img name=select2 src=\"inc/gfx/opentriangle.gif\" border=0/>&nbsp;</b></a>";
		//echo "&nbsp;<a class=bouton_htdtc href=\"javascript:void(0)\" onmouseover=\"select2.src='inc/gfx/opentriangle_over.gif',AffBulle('<table class=insert_htdtc cellspacing=2 cellpadding=2 onclick=\'HideBulle()\'><tr><td align=right colspan=7><img class=shadow_htdtc alt=Fermer onmouseover=close2.src=\'inc/gfx/close_over.gif\' onmouseout=close2.src=\'inc/gfx/close.gif\' name=close2 src=\'inc/gfx/close.gif\' align=abstop border=0 onclick=\'HideBulle()\'></td></tr><tr><td>&nbsp;<img src=\'inc/gfx/apphoto.gif\' align=absmiddle border=0>";ShowFoldersForInsert(IMGDIR,'apphoto','pics'); echo "</td></tr><tr><td>&nbsp;<img src=\'inc/gfx/pdf_x.gif\' align=absmiddle border=0>";ShowFoldersForInsert(PDFDIR,'apphoto','pdf'); echo "<tr><td>&nbsp;<img src=\'inc/gfx/page_x.gif\' align=absmiddle border=0>";ShowFoldersForInsert(POPDIR,'page_x','pop'); echo "</td></tr><tr><td height=10 class=corps_htdtc></td></tr></table>')\" onmouseout=\"select2.src='inc/gfx/opentriangle.gif'\"><b>&nbsp;Inserer&nbsp;<img name=select2 src=\"inc/gfx/opentriangle.gif\" border=0/>&nbsp;</b></a>";
	}

	function OtherFolders()
	{
		echo "<a class=bouton_htdtc href=\"javascript:void(0)\" onmouseover=\"selecto.src='inc/gfx/folder2_over.gif',AffBulle('<table class=insert_htdtc cellspacing=1 cellpadding=1 onClick=\'HideBulle()\'><tr><td align=right><img class=shadow_htdtc alt=Fermer onMouseOver=close3.src=\'inc/gfx/close_over.gif\' onMouseOUT=close3.src=\'inc/gfx/close.gif\' name=close3 src=\'inc/gfx/close.gif\' align=\'abstop\' border=0 onClick=\'HideBulle()\'></td><tr><tr><td align=center><img src=\'inc/gfx/dossier.gif\' align=\'absmiddle\' border=0>&nbsp;<b>".DIRBUTTONTITLE."&nbsp;</b></td></tr>";ShowFolders(IMGDIR,'apphoto','Pics'); ShowFolders(PDFDIR,'pdf_x','Pdf'); ShowFolders(POPDIR,'page_x','Pop'); echo "<tr><td height=5></td></tr></table>')\" onMouseOut=\"selecto.src='inc/gfx/folder2.gif'\"><img name=selecto src=\"inc/gfx/folder2.gif\" border=0 align=middle /></a>";
	}
}
?>